### ISSUE TITLE
[Control Protocol] Remote Playback API control protocol

### ISSUE THREAD

**Issue by mfoltzgoogle** [webscreens/openscreenprotocol#12]
This work item covers the control protocol for the Remote Playback API, i.e. the syntax and meaning of the messages sent over the transport [1] to start and control remote playback.

It might make sense to pick an initial transport before undertaking this work item, since the format of the control messages may be tied to the transport. For example, we may be able to map control messages onto transport level mechanisms like QUIC resource streams.

[1] #8 Evaluate protocol transport mechanisms

**Comment by mfoltzgoogle** [comment]
FYI @avayvod @mlamouri

**Comment by anssiko** [comment]
FYI the right @mounirlamouri

**Comment by mfoltzgoogle** [comment]
This issue wasn't tagged, but PR #134 added substantial support for the Remote Playback API.  There are several followup issues to improve the initial wire protocol and its definition.   Thanks @pthatcherg!
