### ISSUE TITLE
[Auth] Challenge/Response over TLS

### ISSUE THREAD

**Issue by nigelcearnshaw** [webscreens/openscreenprotocol#122]
Just reviewing the outcome of the [last F2F meeting](https://www.w3.org/2018/10/26-webscreens-minutes.html#x06) during which it was resolved to further investigate the viability of a passcode related non-pake challenge-response mechanism over an already established TLS secure authenticated channel.

Am I right in assuming this requires all displays to be fitted with a confidential private key and corresponding public key certified by a certificate authority commonly trusted by most browsers?
If so, is this typically the case in the current market place?

**Comment by pthatcherg** [comment]
We can discuss this more when I write up the specifics in a PR, but we would not be requiring a certificate signed by a CA.  It will likely require a self-signed certificate, which is a very common technique in p2p systems (for example, all WebRTC endpoints).

**Comment by mfoltzgoogle** [comment]
PR #212 describes the certificates to be used by agents for TLS.  If there are further details needed to specify them, let's track that in a more specific issue.
