### ISSUE TITLE
Is a Presentation close/terminate from a controller a request/response or event?

### ISSUE THREAD

**Issue by pthatcherg** [webscreens/openscreenprotocol#124]
If request/response, that means it can fail, but the web API doesn't allow the JS to know of failure.

If event, it can't fail.

**Comment by btolsch** [comment]
For reference, this issue is forked from the [comments on an earlier PR](https://github.com/webscreens/openscreenprotocol/pull/120#discussion_r238220177).

**Comment by mfoltzgoogle** [comment]
Resolved by PR #184.
