### ISSUE TITLE
How should presentation connections handle not receiving close response?

### ISSUE THREAD

**Issue by baylesj** [webscreens/openscreenprotocol#137]
What should the timeout behavior be if this response never comes?  Resend or give up?

From protocol_connection.h here:

https://chromium-review.googlesource.com/c/openscreen/+/1412264/1/api/public/presentation/presentation_connection.h#171

**Comment by btolsch** [comment]
Related: #124

**Comment by mfoltzgoogle** [comment]
Resolved by PR #184.
