### ISSUE TITLE
[Presentation API] Remove presentation-connection-close-response message

### ISSUE THREAD

**Issue by mfoltzgoogle** [webscreens/openscreenprotocol#138]
The other agent is [not required](https://w3c.github.io/presentation-api/#closing-a-presentationconnection) to wait for acknowledgement that a presentation connection is closed before running the local steps to close the connection:

> Start to signal to the destination browsing context the intention to close the corresponding PresentationConnection, passing the closeReason to that context. The user agent does not need to wait for acknowledgement that the corresponding PresentationConnection was actually closed before proceeding to the next step.

This implies that there is no need for the  `presentation-connection-close-response` in the spec.

**Comment by btolsch** [comment]
Related: #124

**Comment by mfoltzgoogle** [comment]
Resolved by PR #184.
