### ISSUE TITLE
[Protocol] Clarify scoping/uniqueness of request IDs

### ISSUE THREAD

**Issue by mfoltzgoogle** [webscreens/openscreenprotocol#139]
The spec states, 

> A request and a response includes a request ID which is an unsigned integer chosen by the requester. Responses must include the request ID of the request they are associated with.

In implementing the library, we need to know
- Are request IDs unique per-connection or across connections to the same agent? 
- What happens if a request is sent on one connection and a response on another?
- Do they need to be unique across agents/endpoints (implying that some per-endpoint data needs to be mixed in)?

Steps in the spec to allocate the next request ID could address these questions.

**Comment by mfoltzgoogle** [comment]
Additional things to address:

- If we allow the request ID counter to span connections, are the endpoints required to keep this state, or should we add something to the protocol to relay the next request ID on a new connection?
- Do the IDs need to be unique for requests across the client and server sides of the connection? Suggest using even/odd numbers to address this.

**Comment by calvaris** [comment]
I think they should be unique per session to reduce user tracking, right?

**Comment by mfoltzgoogle** [comment]
Re: https://github.com/webscreens/openscreenprotocol/issues/139#issuecomment-470000817

There's no direct relationship between the request and watch IDs and individual users/connections.  It's just a counter that's kept per-device and occasionally reset.  I don't think they would be useful for tracking users, but take a look and see what you think.

**Comment by mfoltzgoogle** [comment]
Resolved by PR #181
