### ISSUE TITLE
Spec's issues index is incomplete, out of date

### ISSUE THREAD

**Issue by baylesj** [webscreens/openscreenprotocol#142]
Currently, we list some issues with the spec in the spec itself, but only 3, 12, and 13. We should probably just remove this section completely, as it doesn't add any value?

**Comment by mfoltzgoogle** [comment]
The index is auto-generated by Bikeshed (the spec processor) from inline GitHub issues.  Cross referencing issue threads helps outside parties review discussion of outstanding issues in the spec.  I'll try to update the inline links to reflect all of the "v1-spec" issues in GitHub.

**Comment by mfoltzgoogle** [comment]
Addressed by PR #161.
