### ISSUE TITLE
Receiver/Controller/Agent terminology

### ISSUE THREAD

**Issue by pthatcherg** [webscreens/openscreenprotocol#144]
What nouns should we use to refer to an impl of OSP on the controller side and receiver side that meshes well with the Presentation API terminology and Remote Playback API terminology?  

I tried to go with something like "controller" and "receiver", but "controller" means a web context, not a user agent in the Presentation API terminology, and "receiver" isn't used in the Remote Playback API terminology.

**Comment by mfoltzgoogle** [comment]
Addressed by PR #211 which hopefully should align terminology across the entire spec.
