### ISSUE TITLE
Watch ID uniqueness

### ISSUE THREAD

**Issue by pthatcherg** [webscreens/openscreenprotocol#145]
How unique are watch IDs?  We should probably have them span QUIC connections.  But since the controller (watcher) chooses them, the receiver (watchee) has to keep a (controller, watch-id) table.  Could we allow the receiver (watchee) to choose the watch-id so it can make them unique across all controllers?  And should the watch-id be unique across all types of watches, or scoped to types of watches?

**Comment by mfoltzgoogle** [comment]
Closing by merging PR #181.
