### ISSUE TITLE
Choosing QUIC connection IDs (or using zero length IDs)

### ISSUE THREAD

**Issue by pthatcherg** [webscreens/openscreenprotocol#169]
In the latest QUIC spec, even short headers include connection IDs (draft-ietf-quic-transport-20).  But it also supports zero-length connection IDs, with some restrictions.

So, we have two choices:

A. Use non-zero length connection IDs.  Pros: we can do connection migration.  Cons: we have so many bytes overhead in every packet (which hurts for media streaming).

B.  Use zero-length connection IDs.  Pros: No overhead.  Cons: no connection migration (must not send from a different (ip, port) without doing a new handshake.

I think it's fine to require a new handshake when changing (ip, port), so I think we should go with B and mandate zero-length connection IDs.  Further, if we ever use ICE in the future, that will handle the connection migration and not QUIC, in which case we would use zero-length connection IDs.

**Comment by pthatcherg** [comment]
PR for option B: https://github.com/webscreens/openscreenprotocol/pull/170

**Comment by mfoltzgoogle** [comment]
Per https://www.w3.org/2019/05/23-webscreens-minutes.html#x13: PR #170 is good for landing to address issue #169

Merged PR #170 and closing this.
