### ISSUE TITLE
Add Extensibility section

### ISSUE THREAD

**Issue by anssiko** [webscreens/openscreenprotocol#175]
Per discussion at F2F, we should add informative section to the OSP spec on how to add extensions and what are the considerations for implementers.

Example: https://w3c.github.io/sensors/#extensibility

F2F minutes reference: https://www.w3.org/2019/05/24-webscreens-minutes.html#x01

**Comment by mfoltzgoogle** [comment]
PR #183 adds the framework for adding new capabilities (extension messages) to the protocol.

What remains to do is to check in a registry of capabilities/extensions.  Leaving this open until that is done :-)

**Comment by mfoltzgoogle** [comment]
Both the framework (in the spec) and the initial capabilities registry (as a separate file) have been landed in the repository, so marking this closed.
