### ISSUE TITLE
Bidirectional streaming / stream request

### ISSUE THREAD

**Issue by mfoltzgoogle** [webscreens/openscreenprotocol#176]
PR #172 describes one agent generating a streaming-session-start-request and receiving a streaming-session-start-response. If both agents want to send media (or data), the spec should describe how a bidirectional session could be started using the protocol.

**Comment by pthatcherg** [comment]
Why not just start two sessions, one in each direction?

**Comment by mfoltzgoogle** [comment]
It would will be more difficult to share a common media and stats timeline with independent sessions.  It will be hard to answer that question until the unidirectional streaming spec is landed.

**Comment by pthatcherg** [comment]
I can't think of any reason why you would need that, but I like the idea of landing everything for unidirectional and then discussing the bidirectional idea more after that.

**Comment by mfoltzgoogle** [comment]
A related use case is when an agent wants to request a stream from another agent, versus pushing a stream.  For example, retrieving input from a webcam or game controller.

The media receiver can initiate a streaming session, but doesn't have a way to find out what streams the media sender has available.

**Comment by mfoltzgoogle** [comment]
At TPAC, it was decided that for now, this use case does not require additional support from the protocol.

https://www.w3.org/2019/09/15-webscreens-minutes.html#x19

An application can decide to request that another agent initiate a streaming session to it (via an application specific protocol), or two applications can initiate two distinct streaming sessions to create a bidirectional streaming situation.
