### ISSUE TITLE
[Security] Consider making auth-initiation-token mandatory.

### ISSUE THREAD

**Issue by mfoltzgoogle** [webscreens/openscreenprotocol#185]
We recommend agents use a token to hand out consent to participate in PSK authentication.

Should we make it mandatory?

What are the implications for agents outside the LAN (how would they get the token)?

Ref: https://github.com/webscreens/openscreenprotocol/pull/182#discussion_r314099812

**Comment by pthatcherg** [comment]
I think we should make it mandatory.  Any non-mDNS discovery mechanism should also provide a token.  The token is proof that you used a discovery mechanism.

**Comment by mfoltzgoogle** [comment]
Closed by PR #189
