### ISSUE TITLE
Define ALPN

### ISSUE THREAD

**Issue by pthatcherg** [webscreens/openscreenprotocol#228]
QUIC requires an ALPN value, so we should pick one and register it with IANA.

How about "osp"?

**Comment by mfoltzgoogle** [comment]
We will need to register it with IANA:

https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids

**Comment by mfoltzgoogle** [comment]
PR #229 adds "osp" to the ALPN to the spec.  I'll close this one and open a new issue for IANA registration since that's not related to the spec itself.
