### ISSUE TITLE
[SSDP] Evaluate power requirements for SSDP discovery

### ISSUE THREAD

**Issue by mfoltzgoogle** [webscreens/openscreenprotocol#23]
If possible to create a controlled environment for power usage, we could measure against mechanism parameters (i.e., MX, search frequency) and the number of controlling and receiving devices.

**Comment by louaybassbouss** [comment]
Yes we can do this by using these node modules peer-ssdp, peer-upnp and peer-dial (all available on npm) to make an experiment with different combination of devices, services, search frequency, etc.

**Comment by mfoltzgoogle** [comment]
Issue #26 is basically a duplicate of this and has more detail, so closing this one.
I'll copy over Louay's comment.
