### ISSUE TITLE
[Meta] Evaluate presentation screen discovery mechanisms

### ISSUE THREAD

**Issue by mfoltzgoogle** [webscreens/openscreenprotocol#5]
This issue covers evaluation of presentation screen discovery mechanisms.

Per the charter scope, the focus will be on LAN discovery mechanisms.  The following have been proposed thus far:

- [x] Multicast DNS/DNS-SD #6
- [x] SSDP/DIAL #7

(If there are any I have missed, please reply to this issue.)

The task for each is to evaluate them along the functional and non-functional requirements, and make an initial recommendation to explore further.

**Comment by mfoltzgoogle** [comment]
The evaluations should cover the following criteria (non-exhaustive):

- Functional
- Reliability
- Ease of implementation / deployment
- Security - both of the implementation, and whether it can be leveraged to enhance security of the entire protocol
- Privacy: what device information is exposed 
- Network efficiency
- Power efficiency
- IPv4 and IPv6 support
- Standardization status

**Comment by louaybassbouss** [comment]
@mfoltzgoogle you can count on me for the discovery part. I will first start with SSDP/DIAL.

**Comment by mwatson2** [comment]
@louaybassbouss Please let me know if I can help with the DIAL related aspects.

**Comment by louaybassbouss** [comment]
@mwatson2 sorry for late reply, yes I will let you know if I need help. I am not sure if in the evaluation of discovery protocols we need to consider DIAL or only SSDP. I think the DIAL API part (POST/GET/DELETE HTTP requests on the /apps/... endpoint) could be evaluated in the "Protocol Signalling". What do you think?

**Comment by chrisn** [comment]
As input to the evaluation, here's some [previous work](https://github.com/bbc/device-discovery-pairing/blob/master/document.md) from myself and a colleague - there may be some useful info on mDNS and SSDP.

**Comment by louaybassbouss** [comment]
@mfoltzgoogle @mwatson2 @chrisn I just submitted the PR #20 which contains the SSDP evaluation. feel free to review and comment.
@mwatson2 I focussed in the document only on the discovery part which is SSDP but discussed how DIAL uses SSDP, Device Description and how it signal the Endpoint of the DIAL Server. We should consider DIAL REST API in the control protocol (#11) evaluation as well. What do you think?

**Comment by mfoltzgoogle** [comment]
We've landed initial evaluations for #6 and #7.  There are some follow up items around security and data collection which are tracked under separate issues linked from the main documents.

@chrisn Apologies, but I missed  https://github.com/webscreens/openscreenprotocol/issues/5#issuecomment-274061834 you made some time ago with the MediaScape report on discovery.  I'll definitively take a look before closing this meta-issue out.

**Comment by mfoltzgoogle** [comment]
@chrisn, I deep linked to your literature review in the README - thanks for noting it as I wasn't familiar with some of the technologies listed.

**Comment by chrisn** [comment]
Many thanks @mfoltzgoogle, I've just edited the review to bring a few parts up to date.
