### ISSUE TITLE
Representation of BCP-47 language tags

### ISSUE THREAD

**Issue by mfoltzgoogle** [webscreens/openscreenprotocol#54]
[BCP-47](https://tools.ietf.org/html/bcp47#section-4.4) states that language tags can be arbitrarily long in theory.

In https://github.com/webscreens/openscreenprotocol/pull/53#issuecomment-331019337 @tomoyukilabs wrote:

> Okay. I just wanted to confirm the reason of 64 characters. Regarding the length, BCP-47 describes Length Considerations and indicates several examples and recommendations, e.g.:
> - historically most language tags have consisted of language and region subtags with a combined total length of up to six characters
> - RFC4646 recommended a minimum field size of 42 characters

This issue is to research real-world usage and/or ask for input from the i18n working group on language tag usage to inform if we want a fixed length string or variable length string.

**Comment by anssiko** [comment]
Closed per F2F resolution https://www.w3.org/2018/05/18-webscreens-minutes.html#x14
