### ISSUE TITLE
Evaluate SSDP/DIAL as a discovery mechanism

### ISSUE THREAD

**Issue by mfoltzgoogle** [webscreens/openscreenprotocol#7]
See the meta-issue #5 for the list of evaluation criteria.

**Comment by louaybassbouss** [comment]
FYI I just assigned this task to myself. I will put evaluation results in a markdown file in the home folder of this repository.

**Comment by louaybassbouss** [comment]
PR #20 contains the initial version of SSDP evaluation. what still TODO is to have concrete numbers for Network and Power efficiency.

**Comment by mfoltzgoogle** [comment]
Closing as this contains a good outline.  We can track some specific questions in followup issues. 

Filed #23 for getting power requirements.
