### ISSUE TITLE
[Protocol] Hand-rolled binary protocol?

### ISSUE THREAD

**Issue by cynthia** [webscreens/openscreenprotocol#77]
As discussed earlier during TPAC, I've noticed that the protocol is a hand-rolled binary protocol. I'm wondering if this is the best way forward, since the spec isn't in a stage whether or not this information should be exposed raw to the application. (I'm guessing in this context, it would be de-serialized in advance by the user agent)

Unfortunately JSON _might_ not be the best option for this use case, since the commands are streamed from what I understand. But using a battle tested serialization format would probably be a better way forward.

RFC7049 http://cbor.io from IETF is one option (also mentioned earlier), but I remember reading something about a technical bug on this - I'll have to dig up the details, but IIRC it was related to unicode handling so this may not apply to your use case.

**Comment by avayvod** [comment]
@rektide 

See https://github.com/webscreens/openscreenprotocol/blob/gh-pages/control_protocol.md#json for why JSON was dismissed.

Also https://github.com/webscreens/openscreenprotocol/blob/gh-pages/control_protocol.md#presentation-application-message for when the messages can contain arbitrary binary data.

**Comment by mfoltzgoogle** [comment]
We're looking at CBOR and protocol buffers as replacements for the API-level protocol messages.  Once we have a consensus on the format, my intention is to replace the hand-rolled messages with one of those formats.  Efficiency for sending binary blobs is one consideration among several here.

**Comment by rakuco** [comment]
@mfoltzgoogle: Reading the [May F2F minutes](https://www.w3.org/2018/05/18-webscreens-minutes.html#x02), it was said that the benchmark results discussed there would also be posted here. Would it be possible to do so?

**Comment by mfoltzgoogle** [comment]
@rakuco I think you're looking for slides 95-97 here: https://www.w3.org/2014/secondscreen/slides/openscreenprotocol-berlin-f2f-2018-google.pdf

**Comment by mfoltzgoogle** [comment]
@pthatcherg landed two PRs (#119, #120) that lay the framework for CBOR-based message passing and how it can be used to implement the Presentation API.  There's still some work to do to finish the message definitions for the Remote Playback API (tracked under Issue #12) and tighten up a few other details.  But I think there's enough to close out this issue, which I'll do in a week if I don't hear otherwise.
