### ISSUE TITLE
[QUIC] Investigate and propose use of DataChannel framing on top of QUIC

### ISSUE THREAD

**Issue by mfoltzgoogle** [webscreens/openscreenprotocol#84]
From https://www.w3.org/2017/11/07-webscreens-minutes.html#x22:

RESOLVED: Take a hybrid approach where we use QUIC as the primary transport protocol, while leveraging RTC data channel features to move to a peer connection in more heterogeneous environments later on.

To take action, we will need to investigate layering an RTCDataChannel on top of QUIC, in such a way that it can be migrated to a PeerConnection later.

There is bleeding edge work going on from some WebRTC folks in this area.  See  https://github.com/aboba/quic.  I will take an action to review this draft and follow up with my WebRTC colleagues.

**Comment by mfoltzgoogle** [comment]
Relevant slides from WebRTC:

https://docs.google.com/presentation/d/1Sg_1TVCcKJvZ8Egz5oa0CP01TC2rNdv9HVu7W38Y4zA/edit#slide=id.p

**Comment by schien** [comment]
It's interesting to see WebRTC is embracing QUIC as well. I can imagining that ICE will need to be integrated into open screen protocol to support heterogeneous network. This might lead to a unified protocol stack for both open screen protocol and WebRTC.

**Comment by anssiko** [comment]
https://www.w3.org/2018/05/17-webscreens-minutes.html#x08

>RESOLVED: For transport, mandate QUIC DataChannel as transport, and mandate DataChannel over UDP mode (without ICE) in v1. Plan is to allow use of ICE with host candidates in v1.5. And integrate ICE + STUN / TURN for network traversal in v2.
